In [4]:
import tensorflow as tf
import numpy as np

In [5]:
# LECTURE 1
# TF variables are evaluated in Sessions

# TensorFlow has lazy evaluation - evaluation only as-needed by sess.run(var)
x = 2
y = 3
op1 = tf.add(x, y)
op2 = tf.multiply(x, y)
op3 = tf.pow(op2, op1)
with tf.Session() as sess:
    op3 = sess.run(op3)
    print(op3)

7776


In [6]:
""" Graphs are useful as they are 
-savable, 
-break a computation down, 
-facilitate parallelism, 
-helps with visualization
"""

# Make a graph to store the nodes & ops
g = tf.Graph()
with g.as_default():
    x = tf.add(3,5)
sess = tf.Session(graph=g)
x = sess.run(x)
print(x)
sess.close()


# We need to not be confused
# between TF's default and user's graph
g1 = tf.get_default_graph() # handle for default graph
g2 = tf.Graph()             # if user wants own graph

print(g1) # graph object + its mem location

8


In [7]:
# LECTURE 2
a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
x = tf.add(2, 3)
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(x))
    print(writer)
    print(sess.graph)
writer.close()

5


In [10]:
# To use .eval()
sess = tf.InteractiveSession()

# tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)
a = tf.constant(2, shape=[2, 2])
a.eval()

array([[2, 2],
       [2, 2]], dtype=int32)

In [11]:
b = tf.constant([2,1], shape=[3,3])
b.eval()

array([[2, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [12]:
# element wise add + mult
b = tf.constant([[0,1], [2,3]])
x = tf.add(a,b, name="add")
y = tf.multiply(a,b, name="mul")
with tf.Session() as sess:
    x, y = sess.run([x, y])
    print(x)
    print(y)

[[2 3]
 [4 5]]
[[0 2]
 [4 6]]


In [13]:
""" INITIALIZING ARRAYS """

# tf.zeros(shape, dtype=tf.float32, name=None)
z = tf.zeros([2, 3], tf.int32)
z.eval()

# tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)
# zeros array w/ same shape as input_tensor

# tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)
# like above

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [14]:
# tf.fill(dims, value, name=None)
z = tf.fill([2, 3], 8)
z.eval()

array([[8, 8, 8],
       [8, 8, 8]], dtype=int32)

In [15]:
# Gives sequence of equidistant spaced floats (comparable to np.linspace)
# tf.linspace(start, stop, num, name=None)
z = tf.linspace(10.0, 13.0, 4)
z.eval()

array([ 10.,  11.,  12.,  13.], dtype=float32)

In [16]:
# - Cannot iterate over Tensor objects

#tf.range(start, limit=None, delta=1, dtype=None, name='range')
z = tf.range(3, 18, 3)
z.eval()

array([ 3,  6,  9, 12, 15], dtype=int32)

In [17]:
""" Random Generation """
tf.set_random_seed(12345)

a = tf.constant([[2,1],[2,2],[3,3]])
# tf.random_shuffle shuffles on the FIRST dimension (shuffles the rows)
tf.random_shuffle(a).eval()

array([[3, 3],
       [2, 1],
       [2, 2]], dtype=int32)

In [18]:
# tf.random_crop randomly crops out a contiguous block with shape
tf.random_crop(a, [2,1]).eval()

array([[2],
       [2]], dtype=int32)

In [19]:
# tf.multinomial(logits, num_samples, seed=None, name=None)
b = tf.constant(np.random.normal(size = (3,4)))
print(tf.multinomial(b, 5).eval())
print(b.eval())

[[3 0 1 1 1]
 [1 0 0 1 0]
 [0 2 3 0 0]]
[[ 0.48935022  2.44783951 -0.04953447  2.03206189]
 [ 1.23686017  0.10103589  0.78255338 -0.13442349]
 [ 0.21058191 -0.73861758  0.40454474  0.56223879]]


In [20]:
# tf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)
print(tf.random_gamma([10], [5, 15]).eval())
# first col uses alpha of 5, second column uses alpha of 15

[[  4.51271057  18.49232101]
 [  3.78059721  19.35827637]
 [  7.75658035  16.08626938]
 [  2.08486557   8.63947105]
 [  5.11643314  12.77067566]
 [  6.2614274   15.50447464]
 [  6.29539204  12.5557127 ]
 [  3.76571584  17.29309464]
 [  2.83922434  21.4325676 ]
 [  7.37905931  12.39077091]]


In [21]:
""" Operations """
# tf.add_n([a,b,c,...]) can add list of elements
# tf.multiply for element-wis
# tf.mul for matrix mult
a = tf.constant([[0,1],[2,3]])
b = tf.constant([[2,3],[4,5]])
print(tf.multiply(a,b).eval())
print(tf.matmul(a,b).eval())

[[ 0  3]
 [ 8 15]]
[[ 4  5]
 [16 21]]


In [22]:
# 0-d tensor is scalar
# 1-d tensor is array
# 2-d tensor is 2-D



In [23]:
""" Constants """
# Constants are stored in the graph
my_const = tf.constant([1.0, 2.0], name="my_const")
# graph stored all the info (yuck)
with tf.Session() as sess:
    print(sess.graph.as_graph_def())

node {
  name: "Add/x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Add/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "Add/x"
  input: "Add/y"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "Mul/x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Mul/y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }

In [24]:
""" Variables """
# Constants are ops, Variable is class with prepackaged ops
a = tf.Variable([[0,1],[2,3]], name="matrix")
W = tf.Variable(tf.zeros([5,9]))

# Variables must be initialized
init = tf.global_variables_initializer() # initialize all
with tf.Session() as sess:
    sess.run(init)
init_ab = tf.variables_initializer([a,W], name="init_aW")

W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())
    

[[-1.4147284   0.67141438  0.35715106 ..., -1.00789714  0.1527507
  -1.01158834]
 [ 0.28320876 -0.17843904 -0.99711877 ..., -0.03668496  0.2334228
   0.02347624]
 [-1.30190384  0.44275504  1.6582154  ..., -1.28856146  0.00697784
  -1.08565784]
 ..., 
 [ 0.98071283 -0.807863   -0.68175375 ..., -0.12007821 -0.08762608
  -0.02093772]
 [ 0.45152414  1.95376241  0.29409152 ..., -0.31934372  1.6227715
   1.31779623]
 [ 0.80390537 -1.00906754  0.98127568 ..., -0.84430921  0.30983922
  -0.57692653]]


In [25]:
W = tf.Variable(10)
W.assign(100) # op, it must be called in Session
Z = tf.Variable(10)
assign_op = Z.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())  # 10 because W.assign(100) has not been called
    sess.run(assign_op)
    print(Z.eval())  # note no initializer needed

10
100


In [26]:
# Can use variable to initialize another variable
# Must initialize both!
W = tf.Variable(2)
U = tf.Variable(2*W)
sess = tf.InteractiveSession()
sess.run(W.initializer)
sess.run(U.initializer)
print(U.eval())

## An InteractiveSession makes self the default Session

4


In [27]:
""" Control Dependencies """
# Defines run order of ops (prevent dependency errors)
# e.g. run 'd' and 'e' only after 'a','b','c'
#with g.control_dependencies([a, b, c]):
    #d = ...
    
""" Placeholders """
# To assemble graph w/o having the data; can supply data after
# No need to load data
# tf.placeholder(dtype, shape=None, name=None)
a = tf.placeholder(tf.float32, shape=[3])
# shape=None allows any data, but many ops need for shape inference
b = tf.constant([5, 5, 5], tf.float32)
c = a + b
with tf.Session() as sess:
    # must have a dictionary of placeholders (supply the data now)
    print(sess.run(c, {a: [1,2,3]}))

[ 6.  7.  8.]


In [28]:
# To feed in multiple values:
#with tf.Session() as sess:
#    for a_value in list_of_values_for_a:
#        print(sess.run(c, {a: a_value}))

# Can feed in nonplaceholders with feed_dict
a = tf.add(2,5)
b = tf.multiply(a,3)
with tf.Session() as sess:
    replace_dict = {a: 15}
    print(sess.run(b, feed_dict=replace_dict))

45


In [ ]:
""" Lazy Loading """
# Problem: Looping with run adds new nodes! (even duplicate)
# Solution: Separate definition from running

# Check if already initialized!

# In __init__, Declare internal attributes (=None)
# Call code if attribute not defined
# e.g. if not self._prediction: (run code), else (do nothing)
